services:
  blastpass:
    build: .
    container_name: service-blastpass
    ports:
      - "3333:3333"
    volumes:
      - vault_data:/app/vaults
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  vault_data:
    driver: local
