services:
  academy-bank:
    build:
      context: .
      dockerfile: Dockerfile
    image: academy-bank
    container_name: service-academy-bank
    ports:
      - "6969:6969"
    volumes:
      - ./academy_bank.db:/home/ctf/academy_bank.db
    restart: unless-stopped

    security_opt:
      - no-new-privileges:true
    read_only: false
    
    # Resource limits to prevent abuse
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.1'
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
