version: '3.8'

services:
  ftp-server:
    build: .
    ports:
      - "2121:2121"
    volumes:
      - ./ftp_data:/app/ftp_root
      - ./ftp_users.db:/app/ftp_users.db
    environment:
      - FTP_PORT=2121
    command: >
      sh -c "make setup && 
             ./user_admin create_user testuser testpass user1 && 
             ./user_admin create_user admin admin123 user2 && 
             ./ftp_server 2121 ftp_users.db ftp_root"
    restart: unless-stopped

  # Optional: A client container for testing
  ftp-client:
    build: .
    depends_on:
      - ftp-server
    command: ["tail", "-f", "/dev/null"]  # Keep container running
    volumes:
      - .:/app
    profiles:
      - testing
